# Generated by Django 2.2.10 on 2020-05-17 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
                ('date_begin', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала')),
                ('date_end', models.DateTimeField(verbose_name='Дата окончания')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Опросник',
                'verbose_name_plural': 'Опросники',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Текст вопроса')),
                ('question_type', models.IntegerField(choices=[(0, 'Text'), (1, 'Choices'), (2, 'Multi choices')])),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questionnaire.Questionnaire', verbose_name='Опросник')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=128, verbose_name='Вариант ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='questionnaire.Question', verbose_name='Вопрос')),
            ],
            options={
                'unique_together': {('question', 'option')},
            },
        ),
        migrations.CreateModel(
            name='AnswerQuestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата прохождения')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Questionnaire', verbose_name='Опросник')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пройденный опрос',
                'verbose_name_plural': 'Пройденные опросы',
            },
        ),
        migrations.CreateModel(
            name='AnswerQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=256, null=True, verbose_name='Ответ')),
                ('answer_questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.AnswerQuestionnaire', verbose_name='Пройденный опрос')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Question', verbose_name='Вопрос')),
            ],
            options={
                'unique_together': {('answer_questionnaire', 'question')},
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_questions', to='questionnaire.AnswerQuestion', verbose_name='Пройденный вопрос')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Option', verbose_name='Вариант')),
            ],
            options={
                'unique_together': {('answer_question', 'option')},
            },
        ),
    ]
